CREATE DATABASE IF NOT EXISTS bai_2;
USE bai_2;

CREATE TABLE NhaCungCap (
    MaNhaCungCap INT AUTO_INCREMENT PRIMARY KEY,
    TenNhaCungCap VARCHAR(100) NOT NULL,
    DiaChi VARCHAR(255) NOT NULL
);

CREATE TABLE PhieuXuat (
    MaPhieu INT AUTO_INCREMENT PRIMARY KEY,
    NgayXuat DATE NOT NULL
);

CREATE TABLE VatTu (
    MaVatTu INT AUTO_INCREMENT PRIMARY KEY,
    TenVatTu VARCHAR(100) UNIQUE NOT NULL
);

CREATE TABLE PhieuNhap (
    MaPhieu INT AUTO_INCREMENT PRIMARY KEY,
    NgayNhap DATE NOT NULL
);

CREATE TABLE DonDatHang (
    MaDonHang INT AUTO_INCREMENT PRIMARY KEY,
    NgayDatHang DATE NOT NULL,
    MaNhaCungCap INT,
    FOREIGN KEY (MaNhaCungCap) REFERENCES NhaCungCap(MaNhaCungCap) ON DELETE CASCADE
);

CREATE TABLE SoDienThoaiNhaCungCap (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    MaNhaCungCap INT,
    SoDienThoai VARCHAR(20) UNIQUE NOT NULL,
    FOREIGN KEY (MaNhaCungCap) REFERENCES NhaCungCap(MaNhaCungCap) ON DELETE CASCADE
);

CREATE TABLE ChiTietPhieuXuat (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    MaPhieu INT,
    MaVatTu INT,
    DonGiaXuat DECIMAL(10,2) CHECK (DonGiaXuat > 0),
    SoLuongXuat INT CHECK (SoLuongXuat >= 0),
    FOREIGN KEY (MaPhieu) REFERENCES PhieuXuat(MaPhieu),
    FOREIGN KEY (MaVatTu) REFERENCES VatTu(MaVatTu)
);

CREATE TABLE ChiTietPhieuNhap (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    MaVatTu INT,
    MaPhieu INT,
    DonGiaNhap DECIMAL(10,2) CHECK (DonGiaNhap > 0),
    SoLuongNhap INT CHECK (SoLuongNhap >= 0),
    FOREIGN KEY (MaPhieu) REFERENCES PhieuNhap(MaPhieu),
    FOREIGN KEY (MaVatTu) REFERENCES VatTu(MaVatTu)
);

CREATE TABLE ChiTietDonDatHang (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    MaVatTu INT,
    MaDonHang INT,
    FOREIGN KEY (MaDonHang) REFERENCES DonDatHang(MaDonHang),
    FOREIGN KEY (MaVatTu) REFERENCES VatTu(MaVatTu)
);

CREATE TABLE CungCap (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    MaDonHang INT,
    MaNhaCungCap INT,
    FOREIGN KEY (MaDonHang) REFERENCES DonDatHang(MaDonHang),
    FOREIGN KEY (MaNhaCungCap) REFERENCES NhaCungCap(MaNhaCungCap)
);
