CREATE DATABASE IF NOT EXISTS bai_2;
USE bai_2;


CREATE TABLE VatTu (
    MaVTu INT PRIMARY KEY,
    TenVTu VARCHAR(50)
);

CREATE TABLE PhieuXuat (
    SoPX INT PRIMARY KEY,
    NgayXuat DATE
);

CREATE TABLE Xuat_VTu (
    SoPX INT,
    MaVTu INT,
    DGXuat DECIMAL(10,2),
    SLXuat INT,
    PRIMARY KEY (SoPX, MaVTu),
    FOREIGN KEY (SoPX) REFERENCES PhieuXuat(SoPX),
    FOREIGN KEY (MaVTu) REFERENCES VatTu(MaVTu)
);

CREATE TABLE PhieuNhap (
    SoPN INT PRIMARY KEY,
    NgayNhap DATE
);

CREATE TABLE Nhap_VTu (
    SoPN INT,
    MaVTu INT,
    DGNhap DECIMAL(10,2),
    SLNhap INT,
    PRIMARY KEY (SoPN, MaVTu),
    FOREIGN KEY (SoPN) REFERENCES PhieuNhap(SoPN),
    FOREIGN KEY (MaVTu) REFERENCES VatTu(MaVTu)
);

CREATE TABLE DonDH (
    SoDH INT AUTO_INCREMENT PRIMARY KEY,
    NgayDH DATE
);

CREATE TABLE DDH_VTu (
    MaVTu INT,
    SoDH INT,
    PRIMARY KEY (MaVTu, SoDH),
    FOREIGN KEY (MaVTu) REFERENCES VatTu(MaVTu),
    FOREIGN KEY (SoDH) REFERENCES DonDH(SoDH)
);

CREATE TABLE NhaCC (
    MaNCC INT PRIMARY KEY,
    TenNCC VARCHAR(50),
    DiaChi VARCHAR(50)
);

CREATE TABLE SDT (
    SDTNCC VARCHAR(10) PRIMARY KEY,
    MaNCC INT,
    FOREIGN KEY (MaNCC) REFERENCES NhaCC(MaNCC)
);

CREATE TABLE DH_NCC (
    SoDH INT,
    MaNCC INT,
    PRIMARY KEY (SoDH, MaNCC),
    FOREIGN KEY (SoDH) REFERENCES DonDH(SoDH),
    FOREIGN KEY (MaNCC) REFERENCES NhaCC(MaNCC)
);
